name: font_gallery
description: An app which showcases the different fonts
publish_to: 'none'
version: 1.1.1+3

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.16
  lottie: ^2.1.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
  - assets/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  color_dark: "#202124"
  image_dark: assets/logo.png

  android_12:
    color: "#FFFFFF"
    image: assets/logo.png
    color_dark: "#202124"
    image_dark: assets/logo.png